const ROMANOS = ["", "I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX", "X"];
const LISTA_16_CURSOS = ["REDACCION UNIVERSITARIA Y ORATORIA", "INGLES", "REALIDAD REGIONAL Y NACIONAL", "EXPRESION ARTISTICA", "DIBUJO DE INGENIERIA", "MATEMATICA BASICA I", "INGLES TECNICO", "INGENIERIA ECONOMICA", "MATEMATICA BASICA II", "CALCULO DIFERENCIAL E INTEGRAL", "CALCULO MULTIVARIABLE", "FISICA GENERAL", "COSTOS Y PRESUPUESTOS", "ESTADISTICA Y PROBABILIDADES", "ECUACIONES DIFERENCIALES", "ESTADISTICA INFERENCIAL"];

const clean = (t) => t ? t.toString().replace(/[^a-zA-Z0-9]/g, "").trim() : "";
const cleanNombre = (t) => t ? t.toString().toUpperCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").trim() : "";
